// Guest types
export const GET_ROOM_DATA = "GET_ROOM_DATA"
export const RESERVATION_CHECK = "RESERVATION_CHECK"
export const RESERVATION_PROP = "RESERVATION_PROP"
export const BOOK_ROOM = "BOOK_ROOM"
export const SHOW_ALERT = "SHOW_ALERT"

// Administrator types
export const GET_RESERVATIONS = "GET_RESERVATIONS"
export const SEND_RESERVATION_PROP_TO_FORM = "SEND_RESERVATION_PROP_TO_FORM"
export const UPDATE_RESERVATION = "UPDATE_RESERVATION"
export const CREATE_RESERVATION = "CREATE_RESERVATION"
